spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/COMPANIMAL
    username: ohgiraffers
    password: ohgiraffers

mybatis:
  mapper-locations: mappers/**/*.xml