spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/companimal
    username: ohgiraffers
    password: ohgiraffers

  mail:
    host: smtp.gmail.com
    port: 587
    username: companimal0@gmail.com
    password: balqrnmcwuiwmyxf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: mappers/**/*.xml